var state={token:sessionStorage.getItem("vcm_token")||"",view:"dashboard",catalogPage:1,categoryPage:1,recipes:[],regexPreview:null};
var $=function(id){return document.getElementById(id)},esc=function(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"})[c]})};
function toast(m){$("toast").textContent=m;$("toast").hidden=false;clearTimeout(toast.t);toast.t=setTimeout(function(){$("toast").hidden=true},3000)}
function disconnect(){sessionStorage.removeItem("vcm_token");state.token="";$("app").hidden=true;$("auth").hidden=false}
async function api(path,opts){opts=opts||{};var h=new Headers(opts.headers||{});h.set("Authorization","Bearer "+state.token);if(opts.body&&!h.has("Content-Type"))h.set("Content-Type","application/json");var r=await fetch(path,Object.assign({},opts,{headers:h})),t=await r.text(),d={};try{d=t?JSON.parse(t):{}}catch(_){d={detail:t}}if(r.status===401){disconnect();throw Error("Authentication expired")}if(!r.ok)throw Error(d.detail||("HTTP "+r.status));return d}
function setView(v){state.view=v;document.querySelectorAll(".view").forEach(function(x){x.classList.remove("active")});document.querySelectorAll(".nav-item").forEach(function(x){x.classList.remove("active")});$("view-"+v).classList.add("active");var b=document.querySelector('[data-view="'+v+'"]');if(b)b.classList.add("active");$("view-title").textContent=v==="regex"?"Regex Studio":v.charAt(0).toUpperCase()+v.slice(1);$("view-kicker").textContent="CONTROL / "+v.toUpperCase();loadView(v).catch(function(e){toast(e.message)})}
async function connect(){var t=$("token").value.trim();if(!t)return;state.token=t;sessionStorage.setItem("vcm_token",t);try{await api("/api/dashboard");$("auth").hidden=true;$("app").hidden=false;$("auth-error").hidden=true;await loadView("dashboard")}catch(e){sessionStorage.removeItem("vcm_token");state.token="";$("auth-error").textContent=e.message;$("auth-error").hidden=false}}
function table(headers,rows){if(!rows.length)return "<div class=\"preview-list empty\">No records found.</div>";return "<table class=\"table\"><thead><tr>"+headers.map(function(h){return "<th>"+esc(h)+"</th>"}).join("")+"</tr></thead><tbody>"+rows.join("")+"</tbody></table>"}
function metric(l,v){return "<div class=\"metric\"><span>"+esc(l)+"</span><strong>"+Number(v||0).toLocaleString()+"</strong></div>"}
async function loadDashboard(){var d=await api("/api/dashboard"),c=d.status&&d.status.counts||{};$("plugin-chip").textContent=d.plugin&&d.plugin.enabled?"VOD Catalog Manager "+(d.plugin.version||"")+" · enabled":"Plugin "+((d.plugin&&d.plugin.version)||"")+" · disabled";$("metrics").innerHTML=metric("Movies",c.movies)+metric("Series",c.series)+metric("Episodes",c.episodes)+metric("Categories",c.categories);var j=d.jobs||[];$("recent-jobs").innerHTML=j.length?j.map(function(x){return "<div class=\"list-item\"><span>"+esc(x.action)+" · "+esc(x.scope||"—")+"</span><span class=\"job-state "+esc(x.state)+"\">"+esc(x.state)+"</span></div>"}).join(""):"<div class=\"muted\">No jobs yet.</div>"}
async function loadCatalog(){var k=$("catalog-kind").value,q=encodeURIComponent($("catalog-query").value.trim()),d=await api("/api/catalog?kind="+k+"&q="+q+"&page="+state.catalogPage+"&page_size=50");$("catalog-meta").textContent=Number(d.total||0).toLocaleString()+" records";$("catalog-page").textContent="Page "+d.page;$("catalog-prev").disabled=d.page<=1;$("catalog-next").disabled=d.page*d.page_size>=d.total;$("catalog-table").innerHTML=table(["ID","Title","Year"],(d.items||[]).map(function(x){return "<tr><td>"+x.id+"</td><td><strong>"+esc(x.name)+"</strong></td><td>"+esc(x.year||"—")+"</td></tr>"}))}
async function loadCategories(){var q=encodeURIComponent($("category-query").value.trim()),d=await api("/api/categories?q="+q+"&page="+state.categoryPage+"&page_size=50");$("category-page").textContent="Page "+d.page;$("category-prev").disabled=d.page<=1;$("category-next").disabled=d.page*d.page_size>=d.total;$("category-table").innerHTML=table(["ID","Name","Type","Account","Movie","Series"],(d.items||[]).map(function(x){return "<tr><td>"+x.id+"</td><td><strong>"+esc(x.name)+"</strong></td><td>"+esc(x.type)+"</td><td>"+x.account_links+"</td><td>"+x.movie_links+"</td><td>"+x.series_links+"</td></tr>"}))}
async function loadRecipes(){var d=await api("/api/regex/recipes");state.recipes=d.recipes||[];$("recipe").innerHTML="<option value=\"\">Custom rule</option>"+state.recipes.map(function(r){return "<option value=\""+esc(r.id)+"\">"+esc(r.name)+"</option>"}).join("")}
function chooseRecipe(){var r=state.recipes.find(function(x){return x.id===$("recipe").value});if(!r)return;$("regex-pattern").value=r.pattern;$("regex-replacement").value=r.replacement;$("regex-warning").textContent=r.explanation||"Review the preview before applying.";$("regex-warning").hidden=false}
async function previewRegex(){var p={scope:$("regex-scope").value,pattern:$("regex-pattern").value,replacement:$("regex-replacement").value,limit:100,case_insensitive:$("regex-case").checked};var d=await api("/api/regex/preview",{method:"POST",body:JSON.stringify(p)});state.regexPreview=d;$("regex-meta").textContent=(d.matches||0)+" matches / "+(d.scanned||0)+" scanned";var rows=(d.changes||[]).slice(0,60);$("regex-preview-table").classList.toggle("empty",!rows.length);$("regex-preview-table").innerHTML=rows.length?rows.map(function(r){return "<div class=\"preview-row\"><code class=\"preview-old\">"+esc(r.old)+"</code><span class=\"arrow\">→</span><code class=\"preview-new\">"+esc(r.new)+"</code></div>"}).join(""):"No changes in sampled rows.";$("regex-queue").disabled=!(d.matches>0)}
function confirmWrite(t,b){$("confirm-title").textContent=t;$("confirm-body").textContent=b;var d=$("confirm-dialog");d.showModal();return new Promise(function(resolve){function done(){d.removeEventListener("close",done);resolve(d.returnValue==="ok")}d.addEventListener("close",done)})}
async function queueRegex(){if(!state.regexPreview)return;if(!await confirmWrite("Queue regex job?","This will write title changes in bounded transactions."))return;var p={scope:$("regex-scope").value,pattern:$("regex-pattern").value,replacement:$("regex-replacement").value,max_rows:Number($("max-rows").value||0),case_insensitive:$("regex-case").checked,confirm:true},d=await api("/api/regex/jobs",{method:"POST",body:JSON.stringify(p)});toast("Queued "+((d.queued&&d.queued.job_id)||"job"));setView("jobs")}
async function categoryWrite(path,payload,title){var preview=await api(path,{method:"POST",body:JSON.stringify(Object.assign({},payload,{confirm:false}))});if(path.indexOf("delete-empty")>=0&&preview.deletable===false)throw Error("Category is not empty.");if(!await confirmWrite(title,JSON.stringify(preview,null,2)))return;await api(path,{method:"POST",body:JSON.stringify(Object.assign({},payload,{confirm:true}))});toast("Operation completed");await loadCategories()}
async function loadJobs(){var d=await api("/api/jobs?limit=100"),rows=(d.jobs||[]).map(function(j){return "<tr><td><code>"+esc(j.task_id)+"</code></td><td>"+esc(j.action)+"</td><td>"+esc(j.scope||"—")+"</td><td class=\"job-state "+esc(j.state)+"\">"+esc(j.state)+"</td><td>"+esc(j.updated_at)+"</td><td><button class=\"ghost job-open\" data-id=\""+esc(j.task_id)+"\">Inspect</button></td></tr>"});$("jobs-table").innerHTML=table(["Task ID","Action","Scope","State","Updated",""],rows);document.querySelectorAll(".job-open").forEach(function(b){b.onclick=function(){inspectJob(b.dataset.id)}})}
async function inspectJob(id){var d=await api("/api/jobs/"+encodeURIComponent(id)),s=d.job&&d.job.state||"unknown";if(s==="queued"||s==="running"){if(await confirmWrite("Cancel job?",JSON.stringify(d.job.meta||{},null,2))){await api("/api/jobs/"+encodeURIComponent(id)+"/cancel",{method:"POST"});toast("Cancellation requested");await loadJobs()}}else await confirmWrite("Job details",JSON.stringify(d.job||{},null,2))}

async function loadDiagnostics(){
  var d=await api("/api/source-health"),r=d.relations||{},a=d.accounts||{};
  $("source-summary").innerHTML=metric("VOD relations",r.total)+metric("Accounts with VOD",a.with_vod_relations)+metric("Inactive-account links",(r.inactive_account_relations||{}).total)+metric("Active VOD accounts",a.active);
  var ext=(d.container_extensions&&d.container_extensions.movies)||[];
  $("source-extensions").innerHTML=ext.length?ext.map(function(x){return "<div class=\"list-item\"><span>"+esc(x.container_extension||"unknown")+"</span><strong>"+Number(x.count||0).toLocaleString()+"</strong></div>"}).join(""):"<div class=\"muted\">No movie extension data.</div>";
  var ie=r.inactive_account_relations||{};
  $("source-inactive").innerHTML="<div class=\"list-item\"><span>Movies</span><strong>"+Number(ie.movies||0).toLocaleString()+"</strong></div><div class=\"list-item\"><span>Series</span><strong>"+Number(ie.series||0).toLocaleString()+"</strong></div><div class=\"list-item\"><span>Episodes</span><strong>"+Number(ie.episodes||0).toLocaleString()+"</strong></div>";
  var accounts=d.top_accounts||[];
  $("source-accounts").innerHTML=table(["ID","State","Priority","Max Streams","Movies","Series","Episodes"],accounts.map(function(x){return "<tr><td>"+x.id+"</td><td>"+(x.is_active?"active":"inactive")+"</td><td>"+x.priority+"</td><td>"+x.max_streams+"</td><td>"+x.movie_relations+"</td><td>"+x.series_relations+"</td><td>"+x.episode_relations+"</td></tr>"}));
}
async function loadIntegrations(){var d=await api("/api/integrations");$("integration-cards").innerHTML=["plex","jellyfin","emby"].map(function(k){return "<div class=\"integration-card\"><strong>"+k.toUpperCase()+"</strong><span>"+(d[k]&&d[k].configured?"Configured":"Not configured")+"</span></div>"}).join("")+"<div class=\"integration-card\"><strong>VOD2MLIB</strong><span>"+esc(d.vod2mlib&&d.vod2mlib.mode||"disabled")+"</span></div>"}
async function loadAudit(){var d=await api("/api/audit?limit=100"),rows=(d.audit||[]).map(function(x){return "<tr><td>"+esc(x.at)+"</td><td>"+esc(x.actor)+"</td><td>"+esc(x.action)+"</td><td><code>"+esc(x.details_json)+"</code></td></tr>"});$("audit-table").innerHTML=table(["At","Actor","Action","Details"],rows)}
async function loadSettings(){var d=await api("/api/settings/public");$("public-settings").innerHTML=Object.keys(d).map(function(k){return "<div class=\"setting\"><span>"+esc(k)+"</span><code>"+esc(d[k])+"</code></div>"}).join("")}
async function loadView(v){if(v==="dashboard")return loadDashboard();if(v==="diagnostics")return loadDiagnostics();if(v==="catalog")return loadCatalog();if(v==="categories")return loadCategories();if(v==="regex"){if(!state.recipes.length)await loadRecipes();return}if(v==="jobs")return loadJobs();if(v==="integrations")return loadIntegrations();if(v==="audit")return loadAudit();if(v==="settings")return loadSettings()}
function wire(){ $("connect").onclick=connect;$("token").onkeydown=function(e){if(e.key==="Enter")connect()};$("disconnect").onclick=disconnect;$("refresh").onclick=function(){loadView(state.view).catch(function(e){toast(e.message)})};document.querySelectorAll(".nav-item").forEach(function(b){b.onclick=function(){setView(b.dataset.view)}});document.querySelectorAll("[data-view-link]").forEach(function(b){b.onclick=function(){setView(b.dataset.viewLink)}});$("catalog-search").onclick=function(){state.catalogPage=1;loadCatalog().catch(function(e){toast(e.message)})};$("catalog-prev").onclick=function(){state.catalogPage--;loadCatalog()};$("catalog-next").onclick=function(){state.catalogPage++;loadCatalog()};$("category-search").onclick=function(){state.categoryPage=1;loadCategories().catch(function(e){toast(e.message)})};$("category-prev").onclick=function(){state.categoryPage--;loadCategories()};$("category-next").onclick=function(){state.categoryPage++;loadCategories()};$("recipe").onchange=chooseRecipe;$("regex-preview").onclick=function(){previewRegex().catch(function(e){toast(e.message)})};$("regex-queue").onclick=function(){queueRegex().catch(function(e){toast(e.message)})};$("jobs-refresh").onclick=function(){loadJobs().catch(function(e){toast(e.message)})};$("source-refresh").onclick=function(){loadDiagnostics().catch(function(e){toast(e.message)})};$("rename-run").onclick=function(){categoryWrite("/api/categories/rename",{category_id:Number($("rename-id").value),new_name:$("rename-name").value},"Rename category?").catch(function(e){toast(e.message)})};$("merge-run").onclick=function(){categoryWrite("/api/categories/merge",{source_category_id:Number($("merge-source").value),target_category_id:Number($("merge-target").value)},"Merge categories?").catch(function(e){toast(e.message)})};$("delete-run").onclick=function(){categoryWrite("/api/categories/delete-empty",{category_id:Number($("delete-id").value)},"Delete empty category?").catch(function(e){toast(e.message)})};$("visibility-run").onclick=function(){categoryWrite("/api/categories/visibility",{account_id:Number($("vis-account").value),category_id:Number($("vis-category").value),enabled:$("vis-state").value==="true"},"Change category visibility?").catch(function(e){toast(e.message)})}}
wire();if(state.token)connect();